<?php

use Bitrix\Main;
use Yandex\Market;

Main\Loader::registerAutoLoadClasses('yandex.market', [
	Market\Api\OAuth2\Token\Table::class => '/lib/api/oauth2/token/table.php',
	Market\Reference\Storage\Table::class => '/lib/reference/storage/table.php',
	Market\Export\Setup\Table::class => '/lib/export/setup/table.php',
	Market\Export\IblockLink\Table::class => '/lib/export/iblocklink/table.php',
	Market\Export\Param\Table::class => '/lib/export/param/table.php',
	Market\Export\ParamValue\Table::class => '/lib/export/paramvalue/table.php',
	Market\Export\Filter\Table::class => '/lib/export/filter/table.php',
	Market\Export\FilterCondition\Table::class => '/lib/export/filtercondition/table.php',
	Market\Export\Delivery\Table::class => '/lib/export/delivery/table.php',
	Market\Export\Promo\Table::class => '/lib/export/promo/table.php',
	Market\Export\PromoProduct\Table::class => '/lib/export/promoproduct/table.php',
	Market\Export\PromoGift\Table::class => '/lib/export/promogift/table.php',
	Market\Export\Track\Table::class => '/lib/export/track/table.php',
	Market\Logger\Table::class => '/lib/logger/table.php',
	Market\Logger\Trading\Table::class => '/lib/logger/trading/table.php',
	Market\Trading\Setup\Table::class => '/lib/trading/setup/table.php',
	Market\Trading\Settings\Table::class => '/lib/trading/settings/table.php',
	Market\Confirmation\Setup\Table::class => '/lib/confirmation/setup/table.php',
	Market\Trading\Service\MarketplaceDbs\Options\Timetable::class => '/lib/trading/service/marketplacedbs/options/timetable.php',
	Market\Trading\Entity\Reference\OutletSelectable::class => '/lib/trading/entity/reference/outletselectable.php',
	Market\Export\Collection\Table::class => '/lib/export/collection/table.php',
	Market\Export\CollectionProduct\Table::class => '/lib/export/collectionproduct/table.php',
	Market\SalesBoost\Product\Table::class => '/lib/salesboost/product/table.php',
	Market\SalesBoost\Setup\Table::class => '/lib/salesboost/setup/table.php',
	Market\Trading\Business\Table::class => '/lib/trading/business/table.php',
	Market\Trading\Campaign\Table::class => '/lib/trading/campaign/table.php',
	Market\Export\Run\Data\EntityExportable::class => '/lib/export/run/data/entityexportable.php',
	Market\Catalog\Card\Table::class => '/lib/catalog/card/table.php',
	Market\Catalog\Product\Table::class => '/lib/catalog/product/table.php',
	Market\Catalog\Segment\Table::class => '/lib/catalog/segment/table.php',
	Market\Catalog\Setup\Table::class => '/lib/catalog/setup/table.php',
]);

class_alias(Market\Api\Exception\TransportException::class, Market\Exceptions\Api\Request::class);

Main\Loader::registerAutoLoadClasses('yandex.market', [
	'\Yandex\Market\Checkout\Handlers'                    => '/lib/checkout/handlers.php',
	'\Yandex\Market\Checkout\ButtonBootstrapClient'       => '/lib/checkout/ButtonBootstrapClient.php',
	'\Yandex\Market\Checkout\Api'                         => '/lib/checkout/api.php',
	'\Yandex\Market\Checkout\ApiResponse'                 => '/lib/checkout/apiresponse.php',
	'\Yandex\Market\Checkout\ApiRouter'                   => '/lib/checkout/apirouter.php',
	'\Yandex\Market\Checkout\DeliveryEvent'               => '/lib/checkout/deliveryevent.php',
	'\Yandex\Market\Checkout\DeliveryStatus'              => '/lib/checkout/deliverystatus.php',
	'\Yandex\Market\Checkout\OrderDeliveryView'           => '/lib/checkout/orderdeliveryview.php',
	'\Yandex\Market\Checkout\CheckoutEvents'              => '/lib/checkout/events.php',
	'\Yandex\Market\Checkout\ColorMapHelper'              => '/lib/checkout/colormaphelper.php',
	'\Yandex\Market\Checkout\ProductIdResolver'           => '/lib/checkout/productidresolver.php',
	'\Yandex\Market\Checkout\ProductImageHelper'          => '/lib/checkout/productimagehelper.php',
	'\Yandex\Market\Checkout\ProductVatHelper'            => '/lib/checkout/productvathelper.php',
	'\Yandex\Market\Checkout\Handlers\BaseHandler'        => '/lib/checkout/handlers/BaseHandler.php',
	'\Yandex\Market\Checkout\Handlers\ApplyPromocodesHandler' => '/lib/checkout/handlers/ApplyPromocodesHandler.php',
	'\Yandex\Market\Checkout\Handlers\CheckBasketHandler' => '/lib/checkout/handlers/CheckBasketHandler.php',
	'\Yandex\Market\Checkout\Handlers\WarehousesHandler'  => '/lib/checkout/handlers/WarehousesHandler.php',
	'\Yandex\Market\Checkout\Services\BasketItemsGrouper'    => '/lib/checkout/services/BasketItemsGrouper.php',
	'\Yandex\Market\Checkout\Services\PromocodeCalculator'  => '/lib/checkout/services/PromocodeCalculator.php',
	'\Yandex\Market\Checkout\Services\BasketPriceValidator'   => '/lib/checkout/services/BasketPriceValidator.php',
	'\Yandex\Market\Checkout\Handlers\OrdersHandler'      => '/lib/checkout/handlers/OrdersHandler.php',
	'\Yandex\Market\Checkout\Handlers\DeliveryHandler'    => '/lib/checkout/handlers/DeliveryHandler.php',
	'\Yandex\Market\Checkout\Handlers\SettingsHandler'    => '/lib/checkout/handlers/SettingsHandler.php',
	'\Yandex\Market\Checkout\Handlers\SetAuthKeyHandler'  => '/lib/checkout/handlers/SetAuthKeyHandler.php',
	'\Yandex\Market\Checkout\Handlers\EndpointsHandler'   => '/lib/checkout/handlers/EndpointsHandler.php',
	'\Yandex\Market\Checkout\Delivery\YandexKitDelivery'  => '/lib/checkout/delivery/yandexkitdelivery.php',
	'\Yandex\Market\Checkout\Controller\Checkout'         => '/lib/checkout/controller/checkout.php',
	'\Yandex\Market\Products\Prices\ChangeTable'          => '/lib/products/prices/changetable.php',
	'\Yandex\Market\Products\Prices\Config'               => '/lib/products/prices/config.php',
	'\Yandex\Market\Products\Prices\Repository'           => '/lib/products/prices/repository.php',
	'\Yandex\Market\Products\Prices\Pricer'               => '/lib/products/prices/pricer.php',
	'\Yandex\Market\Products\Prices\Sender'               => '/lib/products/prices/sender.php',
	'\Yandex\Market\Products\Prices\AgentFacade'          => '/lib/products/prices/agent.php',
	'\Yandex\Market\Products\Prices\EventHandler'         => '/lib/products/prices/eventhandler.php',
	'\Yandex\Market\Products\Prices\Installer'            => '/lib/products/prices/installer.php',
	'\Yandex\Market\Products\Availability\ChangeTable'    => '/lib/products/availability/changetable.php',
	'\Yandex\Market\Products\Availability\Config'         => '/lib/products/availability/config.php',
	'\Yandex\Market\Products\Availability\Repository'       => '/lib/products/availability/repository.php',
	'\Yandex\Market\Products\Availability\StockResolver'  => '/lib/products/availability/stockresolver.php',
	'\Yandex\Market\Products\Availability\Sender'         => '/lib/products/availability/sender.php',
	'\Yandex\Market\Products\Availability\AgentFacade'    => '/lib/products/availability/agent.php',
	'\Yandex\Market\Products\Availability\EventHandler' => '/lib/products/availability/eventhandler.php',
	'\Yandex\Market\Products\Availability\Installer'    => '/lib/products/availability/installer.php',
	'\Yandex\Market\Products\ProductsEvents'              => '/lib/products/events.php',
]);

\CJSCore::RegisterExt('ya_pay_sdk', [
    'js' => 'https://pay.yandex.ru/sdk/v1/pay.js',
]);
